### ISSUE TITLE
Error: Empty group is not allowed

### ISSUE THREAD

**Issue by artemklevtsov** [nitely/nim-regex#101]
PCRE seems allow it.

To reproduce:

```nim
import regex

const s = r"(TXT1)/TXT2()\.(\d+)"
let rgs = re(s)
```

The same with `re` is ok.

Can I skip or ignore that?

**Comment by nitely** [comment]
I'll remove that restriction to make it compatible with PCRE.

That said, I think empty groups make no sense. Are you generating that regex or something? if it's hand written, then why would need an empty group?

**Comment by artemklevtsov** [comment]
Thank you for the quick reply. I tried to compile the  [ua-parser/uap-core/regexes.yaml](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml) list.

**Comment by artemklevtsov** [comment]
uap compares groups position with replacements. So we can't simply skip the group.

**Comment by nitely** [comment]
Oh, that's sounds like a valid use case. I'll fix it then.

**Comment by artemklevtsov** [comment]
Seems it not work yet.

Code to reproduce:

```nim
import os
import regex

# nimble install -y https://github.com/nitely/nim-regex
# curl -s https://raw.githubusercontent.com/ua-parser/uap-core/master/regexes.yaml | grep 'regex:' | cut -d ':' -f 2 | tr -d ' ' > /tmp/regexes.txt

let dst = "/tmp" / "regexes.txt"

if dst.fileExists():
  for l in dst.readLines():
    let rgx = re(l)
```
Result:

```bash
nim compile --verbosity:0 --hints:off --run "/tmp/tre.nim"  
/tmp/tre.nim(10, 16) Warning: use readLines with two arguments; readLines is deprecated [Deprecated]
/tmp/tre.nim(11) tre
/home/unikum/Projects/Nim/regex/src/regex.nim(283) re
/home/unikum/Projects/Nim/regex/src/regex/compiler.nim(13) reImpl
/home/unikum/Projects/Nim/regex/src/regex/parser.nim(752) parse
/home/unikum/Projects/Nim/regex/src/regex/parser.nim(666) subParse
/home/unikum/Projects/Nim/regex/src/regex/parser.nim(652) parseGroupTag
/home/unikum/Projects/Nim/regex/src/regex/parser.nim(49) check
Error: unhandled exception: Invalid group. Unknown group type
~8 chars~ntServer)(\d+)(?
                       ^ [RegexError]
Error: execution of an external program failed: '/tmp/tre '
```

**Comment by nitely** [comment]
I see you no longer trust nim-regex :P, but the issue is in your command. I tried `curl -s https://raw.githubusercontent.com/ua-parser/uap-core/master/regexes.yaml | grep -oP "(?<=regex: ').+(?=')" > ./regexes.txt` and your snippet compiles.

**Comment by artemklevtsov** [comment]
My bad sorry. I forgot about around quotes. Now this list compiles successful. Thanks again.
