### ISSUE TITLE
The `.` and multi-line support.

### ISSUE THREAD

**Issue by al6x** [nitely/nim-regex#105]
There's different ways regex libraries threat the `.` character. Like if newline flag is set on or off. The snippet from the docs of `nim-regex`

> .          any character except new line (includes new line with s flag)

I personally find it more confusion than help (like the need to use `[\s\S]` in JavaScript). 

Wouldn't it be better to make it more consistent? And make the `.` to consistently and always match **ANY** character?

**Comment by nitely** [comment]
Yes, but this libraries keeps compatibility with PCRE as much as possible,
