### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by dsfbkenbkxcvbkasfknxczv** [nitely/nim-regex#106]
hi , i got an error when i tring to use regex.
Error: cannot open file: regex
i have installed regex with nimble , exec "nimble path regex" shows i got regex in D:\Nim\bin\pkgs\regex-0.19.0
but i cant import regex .
nim version : Nim Compiler Version 1.4.8
nimble version : nimble v0.13.1
Can you tell me what step went wrong?  thanks

**Comment by nitely** [comment]
I'm not a Windows user. 'nimble install regex' and then 'import regex' in
my nim files works for me on Linux. I'd recommend you to ask for help in
the Nim IRC channel or discord.

**Comment by dsfbkenbkxcvbkasfknxczv** [comment]
ok thanks
