### ISSUE TITLE
Would you possibly add a new tag including patches for stricteffects?

### ISSUE THREAD

**Issue by ringabout** [nitely/nim-regex#116]
Hello @nitely

Some packages depend on `nim-regex` and without the [patch](https://github.com/nitely/nim-regex/pull/110) for stricteffects, they cannot pass tests of https://github.com/nim-lang/Nim/pull/19380 and it will be enabled for v2.

**Comment by nitely** [comment]
done

**Comment by ringabout** [comment]
Thank you!
