### ISSUE TITLE
Regex multiline not working with beginning of line

### ISSUE THREAD

**Issue by jyapayne** [nitely/nim-regex#13]
Awesome work on nim-regex! There is one issue that I'm experiencing but may just be using incorrectly.

@genotrance and I are working on replacing nimgen's nre dependency with your pure Nim solution. However, there is one snag where your library performs something different than I expect.

Given the code:

```nim

import regex

var input = """foo
           bar
   baxx
             bazz
"""

echo input.replace(re"(?m)^", "//")
```

The output is:

```
//f//o//o//
// // // // // // // // // // // //b//a//r//
// // // //b//a//x//x//
// // // // // // // // // // // // // //b//a//z//z/
```

But I would expect it to be:

```
//foo
//           bar
//   baxx
//             bazz
```

which is what I get if I directly replace `import regex` with `import nre` in the above code. Am I misunderstanding how the multiline is working?

**Comment by nitely** [comment]
I know why this occurs, I'll fix it in a couple of hours. It seems `nre` works as you expect and `re` never returns (there's an infinite loop). I'm surprise there is no infinite loop here, since this function is based on `re` :sweat_smile: .

**Comment by nitely** [comment]
here is an alternative btw `input.replace(re"(?m)^(.*\n?)", "//$1")`

**Comment by jyapayne** [comment]
@nitely cool, thanks, that works in the meantime!
