### ISSUE TITLE
A question about the operation of Re

### ISSUE THREAD

**Issue by Sznymo** [nitely/nim-regex#132]
I have a question if i understand correctly 
re2 (compiles with the program),
re (runs dynamically and you can load data while the program is running) 
in the documentation re is described as obsolete, is there a way to load a file from re2 while the program is running ?

**Comment by nitely** [comment]
[re2 can compile a regex at runtime](https://nitely.github.io/nim-regex/regex.html#re2%2Cstring) and compile time. The rest of APIs taking Regex2 as parameter can be used at both compile time and runtime too.

**Comment by nitely** [comment]
Closing. If you need help with this post a little code snippet and I may be able to help. You can always re-open.

**Comment by Sznymo** [comment]
Thank you for your reply :) Will try to rewrite from re to re2 myself. Sorry for writing back so slowly
