### ISSUE TITLE
on latest devel, Error: type mismatch: got <nil> but expected 'string'

### ISSUE THREAD

**Issue by timotheecour** [nitely/nim-regex#17]
nil strings are now an error, breaking this package

see https://github.com/nim-lang/Nim/issues/8667 for a test case

## workaround: --nilseqs:on

**Comment by nitely** [comment]
Thanks for reporting this!

**Comment by timotheecour** [comment]
sure! but what about the other usages? eg I see `isNil` being used in some places where it's a string or seq

```
n.name.isNil # suspicious

type
  ElasticSeq[T] = object
    ## a seq that can grow and shrink
    ## avoiding excessive allocations
    s: seq[T]
    pos: int

proc isInitialized[T](ls: ElasticSeq[T]): bool =
  not ls.s.isNil and ls.s.len > 0 . # definitely suspicious
```

maybe the tests don't cover these code paths?

**Comment by nitely** [comment]
I want to keep supporting Nim >= 0.17.2 for the time being, so I think we'll have to live with that for a while.

**Comment by timotheecour** [comment]
but what about using `s.len == 0` ? then no more warning, and still would support older nim

**Comment by nitely** [comment]
I was not aware that worked on older versions. I'll fix those then :+1:

**Comment by timotheecour** [comment]
oh, sorry please double check first that it works! I just assumed it always worked

**Comment by nitely** [comment]
https://github.com/nitely/nim-regex/commit/fdb3299534c6094746b03c4c4181cd60649ee1cc

**Comment by timotheecour** [comment]
is the `todo: remove in Nim 0.18.1` still relevant?

**Comment by nitely** [comment]
Yes, otherwise it won't work on Nim 0.17.2, I think it'd be ok to drop support for it, though.
