### ISSUE TITLE
latest commit makes `nimble install regex` fail => invalid regex.nimble is invalid

### ISSUE THREAD

**Issue by timotheecour** [nitely/nim-regex#18]
nimble install regex
```
Downloading https://github.com/nitely/nim-regex using git
       Tip: 6 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_23655/githubcom_nitelynimregex/regex.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...         ^.
```

=> could future bugs like this be avoided with a proper check in travis.yml?

**Comment by nitely** [comment]
I didn't break it AFAIK. It's an issue with latest Nimble probably, nothing I can do about it (not by changing travis anyway), I mean Nimble can break backward compatibility at any time.

**Comment by timotheecour** [comment]
upon further debugging:

```
nimble --verbose build
    Setting Nim stdlib prefix to
    Setting Nim stdlib path to /Users/timothee/git_clone/nim/Nim/lib
       Info /Users/timothee/git_clone/timotheecour/timconfig/dots_rename/config/nim.cfg(35, 3) Error: invalid command line option: '--nilseqs'
       Info   --nilseqs:on
     Error: Could not read package info file in /Users/timothee/git_clone/nim/nim-regex/regex.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...         ^.
```

this happens because I have `--nilseqs:on` in my ~/.config/nim.cfg
NOTE: this `--nilseqs:on` must be supported in ~/.config/nim.cfg even now that https://github.com/nitely/nim-regex/commit/e69a8cfb0db4638f9989593a41450ad5f8258a84 was commited, because other packages may require (temporarily...) this flag.

I now agree, though, that it's an issue with nimble

**Comment by nitely** [comment]
https://github.com/nitely/nim-regex/commit/fdb3299534c6094746b03c4c4181cd60649ee1cc

**Comment by timotheecour** [comment]
thanks, indeed works now!
