### ISSUE TITLE
`re` can't use a runtime value: `Error: cannot evaluate at compile time:` 

### ISSUE THREAD

**Issue by timotheecour** [nitely/nim-regex#22]
std/re and std/nre can both use `re` with a runtime value, but not nim-regex

```nim
when defined(case2):
  # ok
  import std/nre
  let pattern = "foo"
  let a = re(pattern)

# EDIT: added
when defined(case3):
  import std/re
  let pattern = "foo"
  let a = re(pattern)

# EDIT: added
when defined(case4):
  # Error: cannot evaluate at compile time: pattern
  import pkg/regex
  let pattern = "foo"
  let a = re(pattern)
```

it's the root cause of https://github.com/citycide/glob/issues/34

**Comment by nitely** [comment]
`re` only works at compile time, but `toPattern` works at runtime (when assigned to let/var) or compiletime (when assigned to const). Btw, you should use raw strings for regex `r"foo"`

**Comment by timotheecour** [comment]
> Btw, you should use raw strings for regex r"foo"

I know about `r"foo"` ; but in some use cases my pattern is only known at runtime, not CT.

> re only works at compile time, but toPattern works at runtime (when assigned to let/var) or compiletime (when assigned to const)

indeed, didn't know about `toPattern` ; seems to work for that; thanks!

 -[ ]  why not  `toPattern` 's definition for `re` so we only need `re`, not `toPattern` ? Are there any advantages to having both ?

**Comment by nitely** [comment]
> -[ ] why not toPattern 's definition for re so we only need re, not toPattern ? Are there any advantages to having both ?

so there's no need to assign it to a const to have it compile at compile-time. I usually pass the regex to some of the APIs and most people (for what I have seen) do that too.
