### ISSUE TITLE
regex is broken on #head

### ISSUE THREAD

**Issue by genotrance** [nitely/nim-regex#32]
Latest 0.8.1 release is broken on #head. Running `nim check regex.nim` results in:

```
regex.nim(211, 21) Error: ambiguous call; both unicode.align(s: string, count: Natural, padding: Rune)[declared in ..\..\..\..\..\..\nimdevel\lib\pure\unicode.nim(1956, 5)] and strutils.align(s: string, count: Natural, padding: char)[declared in ..\..\..\..\..\..\nimdevel\lib\pure\strutils.nim(1132, 5)] match for: (string, int)
```

**Comment by nitely** [comment]
dev version (0.9.1) has this fixed. Sadly, it only supports Nim 0.19. Will this be a problem for nimgen?.  think I can add support for Nim 0.18 back if needed (and even Nim 0.17 maybe)

**Comment by nitely** [comment]
Be aware nim-regex 0.8 does not support Nim 0.17. So, if no one has complained, that's a good sign :sweat_smile:

**Comment by genotrance** [comment]
I've been trying to support all nimgen wrappers from 0.18.0 to #head - effectively n-2 but it's been hard due to various issues.

Will be great if regex went that far back, one less thing to worry about. It will also make the regex package that much more dependable and replace pcre wrapper based modules.

**Comment by genotrance** [comment]
Wow thank you!
