### ISSUE TITLE
can't use at runtime in js mode

### ISSUE THREAD

**Issue by timotheecour** [nitely/nim-regex#37]
this gives CT error with: `nim js -d:case1 main.nim`

```nim
#[
KEY BUG nim regex js D20190529T141136:here

nim-regex/src/regex.nim(687, 3) Error: internal error: genAddr: nkStmtListExpr
    assert i < ls.pos
]#

import pkg/regex

proc main()=
  when defined case1:
    let reg = "a" # BUG

  else:
    const reg = "a" # OK
  let r = re(reg)

main()
```

related: https://github.com/nitely/nim-regex/issues/9

**Comment by nitely** [comment]
I opened a ticket in the Nim repo [0]. But I'll fix this later some other way (the ElasticSeq should be removed and replace by a regular seq)

[0] https://github.com/nim-lang/Nim/issues/11354

**Comment by nitely** [comment]
I fixes this, however the test suite fails [0]. I tried a reduce sample of the test suite using doAssert and it worked...

[0] https://github.com/nitely/nim-regex/issues/38
