### ISSUE TITLE
Support matching at compile-time

### ISSUE THREAD

**Issue by nitely** [nitely/nim-regex#4]
Currently matching won't work due to https://github.com/nim-lang/Nim/issues/7059 IIRC. Matching ASCII *should* work (i.e: `re"(?-u)regex"`

**Comment by nitely** [comment]
Work:

```nim
static:
  doAssert("a".match(re"(?-u)\w+").isSome)
```

Does not work:

```nim
static:
  doAssert("a".match(re"\w+").isSome)
```

**Comment by timotheecour** [comment]
for reference: this gives an error such as:
```
Error: internal error: (filename: "/pathto/Nim/compiler/vmgen.nim", line: 180, column: 16)
```

**Comment by timotheecour** [comment]
see PR https://github.com/nitely/nim-unicodedb/pull/7 that fixes this (rather ugly but can't find better)

**Comment by timotheecour** [comment]
@nitely shall we close this now that https://github.com/nitely/nim-unicodedb/pull/7 was merged?

**Comment by nitely** [comment]
I think word boundary (/b) doesn't work because it needs a similar trick
for some other trie, but I didn't find time to try.

**Comment by timotheecour** [comment]
these all work (see below); any other example you think could be problematic?

```nim
when defined(case1):
  import pkg/regex
  proc main()=
    var m: RegexMatch
    doAssert "a".match(re"\w+", m)
    echo m.captures[0]

  static:
    main()

when defined(case2):
  import pkg/regex
  proc main()=
    var m: RegexMatch
    doAssert "a".match(re"\b\w+", m)

  static:
    main()

when defined(case3):
  import pkg/regex
  proc main()=
    let
      expected = ["a1 ", "b2 ", "c3 "]
      text = "a1 b2 c3 "
    var m: RegexMatch
    doAssert text.match(re"(?P<foo>\b\w{2} ?)+", m)
    var i = 0
    for bounds in m.group("foo"):
      echo (i, expected[i], text[bounds])
      doAssert(expected[i] == text[bounds])
      inc i

  static:
    main()
```

**Comment by nitely** [comment]
It seems just this one fails, which uses `unicodeCategory`:

```nim
static:
    var m: RegexMatch
    doAssert "a".match(re"\pL", m)
```

**Comment by nitely** [comment]
Also, I've to make the test suite run at compile time beore closing this, basically removing `unittest` and using block/doAssert instead. I can do that over the weekend.

**Comment by timotheecour** [comment]
related: https://github.com/nim-lang/Nim/issues/10129 (shouldn't be hard to patch unittest to work at CT but ya, no need to block on `unittest` either)
