### ISSUE TITLE
Request to make the compilation pass with --styleCheck:error

### ISSUE THREAD

**Issue by kaushalmodi** [nitely/nim-regex#41]
Hello,

At least as of nim 0.20.0, compiling regex.nim with the `--styleCheck:error` switch throws error. 

Once the style issues are fixes, those errors will go away. 

The thing is that compilation with styleCheck for my project will fail too if it depends on a non-styleCheck compliant project. That's how I ended up opening this issue. 

---

To enforce that this project always remains styleCheck compliant after all the current issues are fixed, you should create a `config.nims` in the root of this repo with this in it: `switch("styleCheck", "error")`. 

---

Ref: https://github.com/nim-lang/Nim/issues/11756

**Comment by nitely** [comment]
I wonder why is nimpretty checking third party libraries instead of just *your* code, otherwise every library out there must pass the checking. I wonder if there is a way to ignore modules imported with `pkg/` or something.

**Comment by nitely** [comment]
fixed in #40
