### ISSUE TITLE
install error, 'typeDesc'

### ISSUE THREAD

**Issue by Rachael-rq** [nitely/nim-regex#42]
Hi,

Installing the package with nim v20 triggered an error:

`  
     Error: Could not read package info file in /nim-regex/regex.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /nim/lib/system.nim(394, 37) Error: 'typeDesc' should be: 'typedesc'
        ... printPkgInfo() failed.
`

Any suggestion of how to fix this? 

Thanks!
Ruqian

**Comment by nitely** [comment]
Please, share the `nim --version` output.

This has to do with the `styleCheck` flag. Adding that flag to regex's `config.nims` didn't enable it for a library requiring regex... but maybe it does?

CC @kaushalmodi

**Comment by kaushalmodi** [comment]
The `styleCheck` flag should not be running for nim version <= 0.20.2.

@Rachael-rq Have you built your nim from the `devel` branch? (I guess would be that). If so, please rebuild it from devel or use the latest stable release as of today: version 0.20.2.

The line is your error message was fixed in devel in https://github.com/nim-lang/Nim/commit/ff4a9a226f484e3c07c0d2fb2e9ae74e2047a312.

**Comment by narimiran** [comment]
> was fixed in devel

This fix is present also in Nim v0.20.2.

**Comment by Rachael-rq** [comment]
> The `styleCheck` flag should not be running for nim version <= 0.20.2.
> 
> @Rachael-rq Have you built your nim from the `devel` branch? (I guess would be that). If so, please rebuild it from devel or use the latest stable release as of today: version 0.20.2.
> 
> The line is your error message was fixed in devel in [nim-lang/Nim@ff4a9a2](https://github.com/nim-lang/Nim/commit/ff4a9a226f484e3c07c0d2fb2e9ae74e2047a312).

Thanks guys, yes, I think I built the devel branch of Nim
So Previously I had:

`[root@e847c4de5acb /]# git clone https://github.com/nitely/nim-regex/
Initialized empty Git repository in /nim-regex/.git/
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 730 (delta 22), reused 38 (delta 14), pack-reused 681
Receiving objects: 100% (730/730), 226.76 KiB | 334 KiB/s, done.
Resolving deltas: 100% (368/368), done.
[root@e847c4de5acb /]# cd nim-regex/
[root@e847c4de5acb nim-regex]# ll
total 32
-rw-r--r-- 1 root root 1330 Jul 20 04:04 CHANGELOG.md
-rw-r--r-- 1 root root  136 Jul 20 04:04 config.nims
drwxr-xr-x 2 root root 4096 Jul 20 04:04 docs
-rw-r--r-- 1 root root 1079 Jul 20 04:04 LICENSE
-rw-r--r-- 1 root root  797 Jul 20 04:04 README.md
-rw-r--r-- 1 root root  697 Jul 20 04:04 regex.nimble
drwxr-xr-x 2 root root 4096 Jul 20 04:04 src
drwxr-xr-x 2 root root 4096 Jul 20 04:04 tests
[root@e847c4de5acb nim-regex]# nimble install -y
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /nim-regex/regex.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     /nim/lib/system.nim(394, 37) Error: 'typeDesc' should be: 'typedesc'
        ... printPkgInfo() failed.
[root@e847c4de5acb nim-regex]# nim --version
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-10
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: bd689849f28ba98b9b2581605234a2b52fb2e392
active boot switches: -d:release`


It now builds successfully with the

`(base) rlyu@mc02:/mnt/mcfiles/rlyu/Projects/Docker-images$ docker run -it be7626bb8a1c bash
ni[root@a047c03a4192 /]# nim --version
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-19
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: a5d6080a81486412e7567658fa816c475e27e42c
active boot switches: -d:release
`
Thanks,
Ruqian
