### ISSUE TITLE
raiseOSError under windows10

### ISSUE THREAD

**Issue by huaxk** [nitely/nim-regex#48]
code as follow:
```
import regex

var content = "content".replace(re"t", "b")
```
raise exception when complier using nim1.0 under windows10 chinese version:
```
oserr.nim(94)            raiseOSError
Error: unhandled exception: 文件名、目录名或卷标语法不正确。
 [OSError]
```

**Comment by nitely** [comment]
I can't reproduce on Linux, and I don't have a win machine. Please, show the full traceback.

**Comment by nitely** [comment]
Looks like you've hit this bug: https://github.com/nim-lang/Nim/issues/12242 , try Nim 1.0.2. It's not related to nim-regex.
