### ISSUE TITLE
Error: attempting to call undeclared routine

### ISSUE THREAD

**Issue by cabhishek** [nitely/nim-regex#5]
I did `nimble install regex`. And in my `main.nim` I have:
```
import regex
echo "a".isMatch(re"a")
```
`nim c -r main.nim` results in  

`main.nim(2, 9) Error: attempting to call undeclared routine: 'isMatch'`

`nimble path regex` resolves  to `~/.nimble/pkgs/regex-0.6.1/src`.  

Is there an issue with how `nim-regex` is installed via nimble since there is no `/src` inside `~/.nimble/pkgs/regex-0.6.1/` ?

```
nimble -V
nimble v0.8.10 compiled at 2018-03-01 14:40:48
git hash: couldn't determine git hash
```
and
```
nim -v
Nim Compiler Version 0.18.0 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 855956bf617f68ac0be3717329e9e1181e5dc0c6
active boot switches: -d:release

```

**Comment by nitely** [comment]
`isMatch` does not exists. I'm guessing you have taken it from the tests, but the tests have [their own utilities](https://nitely.github.io/nim-regex/).

**Comment by cabhishek** [comment]
@nitely My bad. Thanks.
```
import regex
echo "abcd".find(re"bc").isSome
```
works great.

**Comment by nitely** [comment]
np. `re"bc" in "abcd"` is probably better just for checking.
