### ISSUE TITLE
Non-greedy ? operator broken in 0.14.0

### ISSUE THREAD

**Issue by genotrance** [nitely/nim-regex#61]
Found in nimterop CI.

```nim
import regex

var a = "void __mingw_setusermatherr (int (__attribute__((__cdecl__)) *)(struct _exception *));"

echo a.replace(re"__attribute__[ ]*\(\(.*?\)\)([ ,;])", "$1")

# v0.13.1 => "void __mingw_setusermatherr (int ( *)(struct _exception *));"
# v0.14.0 => "void __mingw_setusermatherr (int (;"
```

Basically, `.*?` matches to the last `))` near the end of the line instead of the first `))`.

**Comment by nitely** [comment]
This works in both versions: `__attribute__[ ]*\(\(.*?\)\)(.*?[ ,;])`. The previous version (v0.13.1) is the buggy one.

Let me know if this fixes it. Thanks for reporting this!

**Comment by nitely** [comment]
Wait, I think I'm wrong. That expression should match until the first `))`.

**Comment by genotrance** [comment]
Yes - 0.13.1 is what we want.
