### ISSUE TITLE
regression: ^ incorrect  when start != 0

### ISSUE THREAD

**Issue by timotheecour** [nitely/nim-regex#64]
/cc @nitely 
I was having a weird error in some program until I traced it back to a regression in nim-regex:

```nim
when true: # D20200501T000945
  import pkg/regex
  proc main()=
    let src = """xabc"""
    let start = 1
    var m: RegexMatch
    let regx = "^abc$".re
    let ok = find(src, regx, m, start = start)
    doAssert ok
  main()
```
ff6ab82: works
master (92ff73c0c3a63d70a7b870dd17e5cd0c23b77282) : fails

git bisect says it's 92ff73c0c3a63d70a7b870dd17e5cd0c23b77282

**Comment by nitely** [comment]
That's `re` and `nre` behaviour. The workaround is to use `match(txt, re"abc", m, start=1)`, or to add `openArray[char]` support so you can pass `toOpenArray(src, 1, src.len-1)` and `start=0`.

**Comment by timotheecour** [comment]
* That's re and nre behaviour
then it seems like a bug that we should report in nim repo
*`match(txt, re"abc", m, start=1)` wouldn't work if my regex is `"^abc"` instead of `"^abc$"` though IIUC

**Comment by nitely** [comment]
> then it seems like a bug that we should report in nim repo

Thank you. I think it's a bug too, but I was trying to convince myself it's a feature :P.

> match(txt, re"abc", m, start=1) wouldn't work if my regex is "^abc" instead of "^abc$" though IIUC

Yeah. That's why I suggested toOpenArray.

Since no other regex library has re/nre behaviour, and no one has reported the previous behaviour to be wrong, I'll mark this as a bug and fix it.

**Comment by timotheecour** [comment]
thanks for the fix! I've submitted https://github.com/nim-lang/Nim/issues/14284

**Comment by timotheecour** [comment]
@nitely so in light of https://github.com/nim-lang/Nim/issues/14284 should we re-open to match re/nre behavior? sorry I was wrong initially on this one, the `start` + preserving `context` argument (eg https://github.com/nim-lang/Nim/issues/14284#issuecomment-626562406 or https://github.com/nim-lang/Nim/issues/14284#issuecomment-626673562) is convincing

**Comment by nitely** [comment]
Yes, I'll revert the changes.
