### ISSUE TITLE
Remove all procs returning Option[T]

### ISSUE THREAD

**Issue by nitely** [nitely/nim-regex#7]
Remove them all in favor of template blocks:

```nim
match("abc", re"abc"):
  assert matched.boundaries == 0 .. 2  # matched var gets injected
```

Can't support both cuz of https://github.com/nim-lang/Nim/issues/7503 . Also, I dislike `Option[T]`

**Comment by dom96** [comment]
Sucks that you have to do this, but perhaps you could rename the procs returning an ``Option[T]``?

**Comment by nitely** [comment]
I'd like to avoid having multiple APIs doing the same thing. I guess I could remove the optional `start` param in the hope that no one uses it and deprecate the APIs properly.

But it seems optional parameters trigger the argument resolution on untyped templates, so I've to do overloading and I'm not sure I want that either :confused:

**Comment by dom96** [comment]
Please don't force users to use a template based API. You don't have to use ``Option[T]``, but only offering templates is inflexible. What if I want to pass the result of a match to one of my functions, even if the match didn't succeed?

**Comment by nitely** [comment]
> What if I want to pass the result of a match to one of my functions, even if the match didn't succeed?

You would pass a `RegexMatch` default value:

```nim
var m: RegexMatch
match(...):
  m = matched
# pass m to some function
```

**Comment by dom96** [comment]
Still, really not a big fan of that. Why not just use ``proc match(s: string, r: RegexPattern, m: var RegexMatch): bool``?

**Comment by nitely** [comment]
I didn't think of it :sweat_smile: 

```nim
var m: RegexMatch
if match("abc", re"abc", m):
   assert m.boundaries == 0 .. 2

# vs

match("abc", re"abc"):
  assert matched.boundaries == 0 .. 2
```

**Comment by nitely** [comment]
Done. https://github.com/nitely/nim-regex/commit/771a9e917da4657aca62372d6e5a2839b7b06d26
