### ISSUE TITLE
Support split with captures

### ISSUE THREAD

**Issue by nitely** [nitely/nim-regex#8]
Apparently this is a useful feature:

```nim
assert "a,b".split(re"(,)") == @["a", ",", "b"]
```

**Comment by hendrikgit** [comment]
Hello, that is a coincidence. I was just about to write you a mail asking if this was possible when I saw this. I'm trying to make docopt work with your nim-regex and found that this is indeed my main problem. If you are adding this feature I'll wait with further workarounds.
Thank you :)

**Comment by nitely** [comment]
I check nim's IRC logs from time to time :smile: . docopt used to have a `split_incl` function [0] when it used re instead of nre, so you use that as a workaround if you need it right now.

[0] https://github.com/docopt/docopt.nim/commit/0aaf814d3c884f83d7d0b232192a4e9dba9a73d2#diff-fb2b8a1303af4bbea06de1907212a8b4L26
