### ISSUE TITLE
docs should be built as part of CI, not generated manually and checked in

### ISSUE THREAD

**Issue by timotheecour** [nitely/nim-regex#87]
now that https://github.com/nitely/nim-regex/pull/86 was merged (yay!) I think docs should be removed and generated via github actions CI on each push to master; eg you can do same as I did here:

https://github.com/nim-lang/fusion/pull/26/files

(and https://github.com/nim-lang/fusion/pull/24/files might or not be needed)

**Comment by nitely** [comment]
Done https://github.com/nitely/nim-regex/blob/e3027aff8a80907b445ce1733fd2e26bd8670a37/.github/workflows/ci.yml#L23-L40
